#!/bin/bash
set -e
if [ "$1" = "configure" ] || [ "$1" = "triggered" ]; then
	if [ -z "${SIMCONF_STATUS:-}" ]; then
		mkdir -p /etc/caraneer-config-nginx;
		exec -a "$0" simconf execute-templates \
			$(if [ -f "/tmp/caraneer-config-nginx.reconfigure" ]; then echo "--reconfigure"; fi) \
			--exec-deb-script \
			"/usr/share/caraneer-config-nginx/templates" \
			"/etc/nginx/conf.d" \
			-- "$@";
	fi;
	DHPARAM_PATH="/etc/caraneer-config-nginx/dh-parameters.4096";
	if
		grep -q "$DHPARAM_PATH" /etc/nginx/conf.d/90-caraneer-config.conf &&
		! [ -f "$DHPARAM_PATH" ];
	then
		openssl dhparam -out "$DHPARAM_PATH" 4096
	fi;
	if deb-systemd-helper deb-systemd-helper-enabled nginx.service; then
		deb-systemd-invoke reload nginx.service || true
	fi
fi;
if [ "$1" = "configure" ] && [ -z "$2" ]; then
		# There was no "old version", therefore this is a new install, so we should make sure nginx is started.
		deb-systemd-invoke enable nginx.service || true
		deb-systemd-invoke start nginx.service || true
fi;
