#!/bin/bash
set -e
if [ "$1" = "purge" ]; then
	if [ -z "${SIMCONF_STATUS:-}" ]; then
		exec -a "$0" simconf purge \
			--exec-deb-script \
			-- "$@";
	fi;
	rm -f /etc/systemd/system/nginx.service.d/00-caraneer.conf;
fi;
